GRANT USAGE ON SCHEMA public TO samrian_app, samrian_auth, samrian_worker;

-- Better Auth owns these tables. Auth credentials cannot access tenant email data.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "accounts" TO samrian_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "apikeys" TO samrian_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "invitations" TO samrian_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "jwks" TO samrian_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "members" TO samrian_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "organization_roles" TO samrian_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "organizations" TO samrian_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "sessions" TO samrian_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "users" TO samrian_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "verifications" TO samrian_auth;

ALTER TABLE "api_idempotency" FORCE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "blocklist" FORCE ROW LEVEL SECURITY;
ALTER TABLE "campaign_mailboxes" FORCE ROW LEVEL SECURITY;
ALTER TABLE "campaign_stats_daily" FORCE ROW LEVEL SECURITY;
ALTER TABLE "campaigns" FORCE ROW LEVEL SECURITY;
ALTER TABLE "contact_assignments" FORCE ROW LEVEL SECURITY;
ALTER TABLE "contact_groups" FORCE ROW LEVEL SECURITY;
ALTER TABLE "contacts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "email_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mailbox_stats_daily" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mailboxes" FORCE ROW LEVEL SECURITY;
ALTER TABLE "notification_prefs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
ALTER TABLE "org_settings" FORCE ROW LEVEL SECURITY;
ALTER TABLE "org_stats_daily" FORCE ROW LEVEL SECURITY;
ALTER TABLE "send_reservations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sender_domains" FORCE ROW LEVEL SECURITY;
ALTER TABLE "thread_reads" FORCE ROW LEVEL SECURITY;
ALTER TABLE "threads" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tracked_links" FORCE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "api_idempotency" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "audit_logs" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "blocklist" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "campaign_mailboxes" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "campaign_stats_daily" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "campaigns" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "contact_assignments" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "contact_groups" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "contacts" TO samrian_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "contacts" TO samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "email_events" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "mailbox_stats_daily" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "mailboxes" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "notification_prefs" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "notifications" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "org_settings" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "org_stats_daily" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "send_reservations" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "sender_domains" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "thread_reads" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "threads" TO samrian_app, samrian_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "tracked_links" TO samrian_app, samrian_worker;
